### ISSUE TITLE
Update for 3.3 VP

### ISSUE THREAD

**Issue by ryanmusante** [TeaDrinkingProgrammer/Civilization-V-Vox-Populi-on-Linux#1] opened 2023-05-08 12:03 UTC
Is this guide still functional for the latest VP update?

**Comment by TeaDrinkingProgrammer** [comment] 2023-05-08 18:18
I haven't looked into the mod and game in a while indeed. That being said, I don't see a reason why it wouldn't work anymore. I will close this issue though, because I cannot solve an issue that mau or may not exist, but if you do run into any issues, don't hesitate to open another one with an explanation of the issue.

**Comment by ryanmusante** [comment] 2023-05-11 01:08
Sorry to bother again but I had a question pertaining to the launcher, was hoping you had advice.

I'm using "ineedlegacyaccess" selected in the tab within Civ5 properties to use the old launcher. What is this selection dialog box seen below? There is no description next to each.

![Screenshot from 2023-05-10 18-06-01](https://github.com/TeaDrinkingProgrammer/Civilization-V-Vox-Populi-on-Linux/assets/26808646/d2fe3f7d-e49f-49f9-a42e-541ed0db2a2f)

**Comment by TeaDrinkingProgrammer** [comment] 2023-05-16 20:21
I do not know, what happens when you click either one? Like I said before, unless you describe a reproducible issue, I cannot help you much.

**Comment by ryanmusante** [comment] 2023-05-20 05:32
It appears, for both, to load the launcher for selecting directx 9/11/tablet. Strange.

**Comment by TeaDrinkingProgrammer** [comment] 2023-05-26 12:02
I am surprised that there are two options, but the launcher doesn't really surprise me. Part of the process of making VP work on Linux is namely using Proton, which means you're essentially playing the Windows version through a compatibility layer. Does it work otherwise?

**Comment by ryanmusante** [comment] 2023-05-26 13:46
Yes, works fine. I'm using proton experimental without any issues.

**Comment by TeaDrinkingProgrammer** [comment] 2023-05-31 09:11
So is there a problem I can help with?

**Closed as completed** 2023-06-08 09:31 UTC
